-- Write SQL queries to perform the following tasks using the Sakila database:

USE sakila;

-- List the number of films per category.

SELECT COUNT(f.film_id) as number_of_films, c.category_id as category
FROM film as f
JOIN film_category as c
ON f.film_id = c.film_id
GROUP BY category_id;

-- Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, co.country
FROM address as a
JOIN store as s ON a.address_id = s.address_id
JOIN city as c ON a.city_id = c.city_id
JOIN country as co ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) as total_revenue
FROM payment as p
JOIN rental as r ON p.rental_id = r.rental_id
JOIN inventory as i ON r.inventory_id = i.inventory_id
JOIN store as s ON i.store_id = s.store_id
GROUP BY s.store_id;


-- Determine the average running time of films for each category.

SELECT c.name as category, ROUND(AVG(f.length),2) as average_running_time
FROM film as f
JOIN film_category as fc ON f.film_id = fc.film_id
JOIN category as c ON fc.category_id = c.category_id
GROUP BY c.name;

-- Identify the film categories with the longest average running time.

SELECT c.name as category, ROUND(AVG(f.length),2) as average_running_time
FROM film as f
JOIN film_category as fc ON f.film_id = fc.film_id
JOIN category as c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY average_running_time DESC
LIMIT 1;